# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Builds the debug code"
  lane :buildDebug do
    gradle(task: "assembleDebug")
  end

    desc "Increment Build number"
  lane :increment_build_number do
    previous_build_number = google_play_track_version_codes(
      package_name: "com.dashxdemo.app",
      track: "internal",
      json_key: "secrets/dashxdemo-playstore-secrets.json",
    )[0]

    current_build_number = previous_build_number + 1

    increment_version_code(
      gradle_file_path: "./app/build.gradle",
      version_code: current_build_number
    )
    end

  desc "Builds the release code"
  lane :buildRelease do
    gradle(task: "bundleRelease")
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Internal Build to Play Store"
  lane :internal do
    upload_to_play_store(track: 'internal', aab: './app/build/outputs/bundle/release/app-release.aab')
  end

  desc "Publish to Internal Testing"
  lane :internal_push do
    buildRelease
    increment_build_number
    internal
   end

#   desc "Promote Internal to Alpha"
#   lane :promote_internal_to_alpha do
#     upload_to_play_store(track: 'internal', track_promote_to: 'alpha')
#   end
#
#   desc "Promote Alpha to Beta"
#   lane :promote_alpha_to_beta do
#     upload_to_play_store(track: 'alpha', track_promote_to: 'beta')
#   end
#
#   desc "Promote Beta to Production"
#   lane :promote_beta_to_production do
#     upload_to_play_store(track: 'beta', track_promote_to: 'production')
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
    #upload_to_play_store
#   end
end
