# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy a internal version to the Google Play"
  lane :internal do
    gradle(task: "bundle", build_type: "StagingRelease", print_command: false,
    properties: {
        "android.injected.signing.store.file" => ENV["ANDROID_KEY_STORE"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEYSTORE_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEYSTORE_KEY_PASSWORD"]

    })
    upload_to_play_store(json_key: ENV["ANDROID_JSON_KEY_FILE"], track: 'internal')
  end

  desc "Responsible for fetching version code from play console and incrementing version code."
  lane :increment_version_code do

      path = '../app/build.gradle'
      re = /versionCode\s+(\d+)/
      version_code_from_play_store_strings = google_play_track_version_codes(
            package_name: "com.dashxdemo.app",
            track: "internal",
            json_key: ENV["ANDROID_JSON_KEY_FILE"],
          )
          version_code_from_play_store = version_code_from_play_store_strings[0].to_i
          UPDATED_VERSION_CODE = version_code_from_play_store + 1
      s = File.read(path)
      s[re, 1] = (UPDATED_VERSION_CODE).to_s
      f = File.new(path, 'w')
      f.write(s)
      f.close

  end

  desc "Deploy a internal version with auto increment of version code"
  lane :internal_with_increment do
        increment_version_code
        fastlane internal
  end

  desc "Deploy a production version to the Google Play"
  lane :production do
    gradle(task: "bundle", build_type: "release", print_command: false,
        properties: {
            "android.injected.signing.store.file" => ENV["ANDROID_KEY_STORE"],
            "android.injected.signing.store.password" => ENV["KEYSTORE_STORE_PASSWORD"],
            "android.injected.signing.key.alias" => ENV["KEYSTORE_KEY_ALIAS"],
            "android.injected.signing.key.password" => ENV["KEYSTORE_KEY_PASSWORD"]

        })
        upload_to_play_store(json_key: ENV["ANDROID_JSON_KEY_FILE"], track: 'production')
  end

  desc "Deploy a production version with auto increment of version code"
    lane :production_with_increment do
          sh "fastlane increment_version_code"
          sh "fastlane production"
  end


end
