# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy a beta version to the Google Play"
  lane :beta do
    gradle(task: "bundle", build_type: "StagingRelease", print_command: false,
    properties: {
        "android.injected.signing.store.file" => ENV["ANDROID_KEY_STORE"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEYSTORE_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEYSTORE_KEY_PASSWORD"]

    })
    upload_to_play_store(json_key: ENV["ANDROID_JSON_KEY_FILE"], track: 'beta')
  end

  desc "Responsible for fetching version code from play console and incrementing version code."
  lane :increment_version_code_in_project_gradle do
    version_code_from_play_store_strings = google_play_track_version_codes(
      package_name: "com.dashxdemo.app",   # PACKAGE_NAME is a global variable defined earlier
      track: "production",          # this can be alpha, beta etc.
      json_key: "/Users/ajaypuli/Documents/dashx-demo-store-secret.json",
    )
    version_code_from_play_store = version_code_from_play_store_strings[0].to_i
    UPDATED_VERSION_CODE = version_code_from_play_store + 1
    increment_version_name(
    bump_type: "patch",
          gradle_file_path: "/Users/ajaypuli/Documents/Github/dashx-demo-android/app/build.gradle",
      version_number: UPDATED_VERSION_CODE.to_i
    )
  end

  lane :IncrementBuildNumber do

      path = '../app/build.gradle'
      re = /versionCode\s+(\d+)/
      s = File.read(path)
      versionCode = s[re, 1].to_i
      s[re, 1] = (versionCode + 1).to_s
      f = File.new(path, 'w')
      f.write(s)
      f.close

  end

  lane :gitpush do

          git_add
          git_commit(path: "*", message: "Version bump")
          push_to_git_remote


  end


  lane :beta_push do
        sh "fastlane IncrementBuildNumber"
        sh "fastlane gitpush"
        sh "fastlane beta"
  end

  desc "Deploy a prod version to the Google Play"
  lane :production do
    gradle(task: "bundle", build_type: "release", print_command: false,
        properties: {
            "android.injected.signing.store.file" => ENV["ANDROID_KEY_STORE"],
            "android.injected.signing.store.password" => ENV["KEYSTORE_STORE_PASSWORD"],
            "android.injected.signing.key.alias" => ENV["KEYSTORE_KEY_ALIAS"],
            "android.injected.signing.key.password" => ENV["KEYSTORE_KEY_PASSWORD"]

        })
        upload_to_play_store(json_key: ENV["ANDROID_JSON_KEY_FILE"], track: 'production')
  end

end
